# Array Operations

## 🔹 1. Element-wise Operations
### These operations apply to each corresponding element of arrays:

In [2]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Addition: ",a+b)
print("Subtraction: ",a-b)
print("Multiplication: ",a*b)
print("Division: ",b/a)

Addition:  [5 7 9]
Subtraction:  [-3 -3 -3]
Multiplication:  [ 4 10 18]
Division:  [4.  2.5 2. ]


## 🔹 2. Aggregation Functions
### These are used to summarize data in arrays:

In [4]:
arr = np.array([1,2,3,4,5])
print("Sum: ",np.sum(arr))
print("Mean: ",np.mean(arr))
print("Standard Deviation: ",np.std(arr))
print("Maximum: ",np.max(arr))
print("Minimum: ",np.min(arr))

Sum:  15
Mean:  3.0
Standard Deviation:  1.4142135623730951
Maximum:  5
Minimum:  1


## With 2D Arrays:


In [7]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])
print("Sum (column - wise): ",np.sum(matrix, axis=0))
print("Sum (row - wise): ", np.sum(matrix, axis=1))

Sum (column - wise):  [5 7 9]
Sum (row - wise):  [ 6 15]


## 🔹 3. Vectorized Operations vs Python Loops
## NumPy is optimized for speed using vectorized operations (internally written in C), while regular Python for loops are slower.

## Let’s compare both:

## 🐢 Python Loop (Slow)

In [10]:
arr = list(range(1,10001))
result =[]
for i in arr:
    result.append(i*2)

## ⚡ Vectorized NumPy (Fast)

In [14]:
import numpy as np
arr = np.arange(1,10001)
result = arr * 2  #vecotrized numpy is not only fast but also shorter and cleaner

## 🔹 4. Dot Product – np.dot()
### For 1D vectors, dot product = sum of products of corresponding elements:

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b)) # 1x4 + 2x5 + 3x6 = 32

32


In [17]:
#Also works on matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))

[[19 22]
 [43 50]]


## 🔹 5. Matrix Multiplication – @ and np.matmul()

In [19]:
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
print(A @ B)
print(np.matmul(A,B))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
