# 🔹 1. Indexing in NumPy
## Indexing works similarly to Python lists, but with added power for multidimensional arrays.

## ✅ 1D Array Indexing

In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0]) #prints first element
print(arr[-1]) # prints last element as first for negative sign

10
50


## ✅ 2D Array Indexing

In [5]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1]) #prints 2 i.e., first row and second column
print(arr[0][1]) #another way
print(arr[1,2]) #second row and third column

2
2
6


# 🔹 2. Slicing in NumPy

## ✅ 1D Array Slicing

In [6]:
arr=np.array([10,20,30,40,50])
print(arr[1:4]) #prints the elements from index 1 to 3 excluding 4
print(arr[:3]) #prints the elements from starting to index 2 excluding 3
print(arr[::2]) #prints every 2nd element i.e., element at 0,2,4

[20 30 40]
[10 20 30]
[10 30 50]


## ✅ 2D Array Slicing

In [11]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(b,"\n")
print(b[0:2, 1:])    # Rows 0–1, Columns 1–end → [[2 3], [5 6]]
print(b[:, 0])       # All rows, column 0 → [1 4 7]
print(b[1])          # Entire second row → [4 5 6]

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]]
[1 4 7]
[4 5 6]


# Question Solving

In [2]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print(arr[2:3])
print(arr[2:6])
print(arr[::2])

[30]
[30 40 50 60]
[10 30 50 70 90]


In [23]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar,"\n")
print(ar[1])
print(ar[:,0])
center_block=ar[1: ,1:]
print(center_block)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[4 5 6]
[1 4 7]
[[5 6]
 [8 9]]


In [34]:
q1=np.array([5,10,15,20,25,30,35,40,45,50])
print(q1[3:8])
print(q1[::3])
print(q1[::-1])

[20 25 30 35 40]
[ 5 20 35 50]
[50 45 40 35 30 25 20 15 10  5]


In [45]:
q2=np.array([
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34],
    [41,42,43,44]])
print(q2,"\n")
print(q2[1])
print(q2[-1])
print(q2[2: ,2:])
print(q2[0:2,2:])

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]] 

[21 22 23 24]
[41 42 43 44]
[[33 34]
 [43 44]]
[[13 14]
 [23 24]]


# 🔹 3. Multi-Dimensional Indexing
## When you're working with 2D, 3D, or higher-dimensional arrays, NumPy lets you access values by specifying an index per axis using commas inside square brackets.



## ✅ Example: 2D Indexing

In [7]:
import numpy as np

arr2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr2d[0, 1])  # 20 → Row 0, Column 1
print(arr2d[2, 2])  # 90 → Row 2, Column 2

20
90


## ✅ Example: 3D Indexing

In [10]:
arr3d = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(arr3d[1, 0, 1])  # 6 → Block 1, Row 0, Column 1


6


## ✅ Shape Reference:

In [11]:
print(arr3d.shape)  # no. of blocks, no. of rows, no. of columns

(2, 2, 2)


## 🧠 Practice:

In [15]:
a = np.array([
    [[10, 11], [12, 13]],
    [[20, 21], [22, 23]],
    [[30, 31], [32, 33]]
])
print(a[1, 1, 0]) #selects the 1st block , row 1 and column 0
print(a[:, 1, 1]) #selects the all blocks , row 1 and column 1
print(a[:,:,1]) #selects the second column for each block

22
[13 23 33]
[[11 13]
 [21 23]
 [31 33]]


# 🔹 4. Boolean Masking (Boolean Indexing)
## ✅ What is it?
## Boolean masking is selecting elements of an array based on a condition. You create a mask (a Boolean array) and use it to filter the elements.

## 📌 Example 1: Simple Masking

In [20]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
mask = arr > 30

print(mask)           # [False False False  True  True]
print(arr[mask])      # [40 50]
print(arr[arr<40])    # another way

[False False False  True  True]
[40 50]
[10 20 30]


## 📌 Example 2: With 2D Arrays

In [23]:
matrix = np.array([
    [5, 10, 15],
    [20, 25, 30]
])

print(matrix > 15)
# Output:
# [[False False False]
#  [ True  True  True]]

print(matrix[matrix > 15])  # [20 25 30]

[[False False False]
 [ True  True  True]]
[20 25 30]


# 📌 Combining Conditions
## Use logical operators like:

## & (and)

## | (or)

## ! (not)

In [30]:
arr = np.array([5, 15, 25, 35, 45])
print(arr[(arr > 15) & (arr < 40)])  # [25 35]
print(arr[(arr > 5) & (arr != 25)])  # [15,35,45]
print(arr[(arr == 5) | (arr < 40)])  # [5,15,25,35]

[25 35]
[15 35 45]
[ 5 15 25 35]


# 🔹 5. Fancy Indexing (Indexing with Lists or Arrays)
## ✅ What is it?
### Fancy indexing lets you access multiple elements at once using lists or arrays of indices — rather than using slices or single positions.

## 📌 Example 1: 1D Fancy Indexing

In [3]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
indices = [1, 3, 4]

print(a[indices])  # [20 40 50]

[20 40 50]


### You can also pass a NumPy array instead of a list:

In [6]:
print(a[np.array([0,2])])

[10 30]


## 📌 Example 2: 2D Fancy Indexing (Row-wise)

In [7]:
matrix = np.array([
    [11, 12],
    [21, 22],
    [31, 32],
    [41, 42]
])

rows = [0, 2, 3]
print(matrix[rows])

[[11 12]
 [31 32]
 [41 42]]


## 📌 Example 3: Selecting Specific Elements (Using Row & Col Arrays Together)

In [41]:
a = np.array([
    [11,12,13],
    [21,22,23],
    [31,32,33],
    [41,42,43]
])
rows = [0,1,2,3] #selecting rows
columns = [1,0,1,2] #selecting specific columns
print(a[rows,columns])


[12 21 32 43]


# 🧠 Practice:

In [42]:
a = np.array([5, 10, 15, 20, 25, 30])
# Try the following:
# Select elements at indices [0, 2, 4]
# Replace elements at indices [1, 3, 5] with 0
# Create a 3×3 matrix of numbers from 1–9 and extract values from positions (0,0), (1,1), (2,2)
print(a[np.array([0,2,4])])
#replacing the values of a at a given index with other value
a[[1,3,5]] = [0,0,0]
print(a)
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
row = [0,1,2]
col = [0,1,2]
print(matrix[row,col])

[ 5 15 25]
[ 5  0 15  0 25  0]
[1 5 9]


# 🔹 4. Conditional Selection in NumPy
## Conditional selection is about choosing or modifying values based on a condition, using tools like:

### boolean masking

### np.where()

### assignment with conditions

# ✅ 1. Basic Conditional Selection

In [43]:
import numpy as np
arr = np.array([10,15,20,25,30])
 #to print elements greater than 20
print(arr[arr>20])

[25 30]


# ✅ 2. Using np.where()
## np.where(condition, value_if_true, value_if_false)

In [44]:
arr = np.array([10,15,20,25,30])
new_arr= np.where(arr > 20, 100 , arr) #if value true then assign 100 to them and if not remain as it as previous array
print(new_arr)

[ 10  15  20 100 100]


# ✅ 3. Chaining Multiple Conditions

In [45]:
arr = np.array([10,15,20,25,30])
# select elements from 10 to 25 inclusively
print(arr[(arr>=10) & (arr<=25)])

[10 15 20 25]


# ✅ 4. Replace Based on Conditions

In [46]:
arr = np.array([3,4,12,8,25,30])
#Replace all values < 10 with 0
arr[arr<10] = 0
print(arr)

[ 0  0 12  0 25 30]


# ✅ 5. With 2D Arrays

In [47]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])
# Get all values greater than 3
print(matrix[matrix>3])

[4 5 6]


# 🧠 Practice Time:

a = np.array([2, 5, 8, 11, 14, 17, 20])

1. Select values that are even
2. Replace all values > 10 with 100
3. Create a new array where:
   - If value is odd, replace with -1
   - Else, keep original


In [48]:
#1
a = np.array([2,5,8,11,14,17,20])
new_arr = a[a % 2 == 0]
print(new_arr)


[ 2  8 14 20]


In [49]:
a = np.array([2,5,8,11,14,17,20])
#2
a[a>10] = 100
print(a)

[  2   5   8 100 100 100 100]


In [50]:
a = np.array([2,5,8,11,14,17,20])
#3
arr1 = np.where(a % 2 != 0,-1,a)
print(arr1)

[ 2 -1  8 -1 14 -1 20]
