# Array Attributes

## NumPy Array Attributes

| Attribute     | Description                                      | Example Output   |
|---------------|--------------------------------------------------|------------------|
| `ndim`        | Number of dimensions (axes)                     | `2`              |
| `shape`       | Tuple showing the shape (rows, cols, ...)       | `(2, 3)`         |
| `size`        | Total number of elements                        | `6`              |
| `dtype`       | Data type of array elements                     | `int64`          |
| `itemsize`    | Memory (in bytes) of one array element          | `8`              |
| `nbytes`      | Total memory used by the array (itemsize × size)| `48`             |
| `T`           | Transpose of the array (flip rows/columns)      | `array([[1, 4], [2, 5], [3, 6]])` |


In [20]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


## 1. arr.ndim

In [10]:
#shows the number of dimensions of array
print("Dimensions:",arr.ndim) # => 1D or 2D array?

Dimensions: 2


## 2. arr.shape

In [12]:
#shows the rows and columns of array
print("Shape:",arr.shape)

Shape: (2, 3)


## 3. arr.size

In [13]:
#shows the total number of elements
print("Size of array:",arr.size)

Size of array: 6


## 4. arr.dtype

In [16]:
#shows the data type of array
print("Data type:",arr.dtype)

Data type: int64


## 5. arr.itemsize

In [23]:
#size in bytes of one(single) element
print("Itemsize:",arr.itemsize)

Itemsize: 8


## 6. arr.nbytes

In [25]:
#Total memory consumed in bytes
print("Memory in bytes:",arr.nbytes)

Memory in bytes: 48


## 7. arr.T

In [28]:
#Transpose(flips rows and columns)
print("Transpose:\n",arr.T)

Transpose:
 [[1 4]
 [2 5]
 [3 6]]
