# #Creating Arrays from Lists and Tuples

## 1.From a list

In [2]:
import numpy as np
arrlst=np.array([1,2,3])
print("Array from list:",arrlst)

Array from list: [1 2 3]


## 2.From a tuple

In [4]:
arrtup=np.array((2,3,4))
print("Array from tuple:",arrtup)

Array from tuple: [2 3 4]


## 2D Array (nested list or tuple)

In [11]:
arr2d=np.array([[1,2,3],[4,5,6]])
print("2D array:\n",arr2d)

2D array:
 [[1 2 3]
 [4 5 6]]


# #Predefined Arrays Using NumPy functions

## 1. np.zeros(shape) =>(row,column)

In [12]:
z=np.zeros((2,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


## 2. np.ones(shape) =>(row,column)

In [15]:
o=np.ones((3,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 3. np.full(shape,fill_value)

In [17]:
f=np.full((2,3),9)
print(f)

[[9 9 9]
 [9 9 9]]


## 4. np.eye(n) >Creates an identity matrix

In [4]:
e=np.eye(4)
print("Identity Matrix:\n", e)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5. np.arange(start, stop, step) >Creates a 1D array of evenly spaced values.

In [3]:
r = np.arange(2, 20, 2)
print("Range array:", r)

Range array: [ 2  4  6  8 10 12 14 16 18]


## 6.  np.linspace(start, stop, num) >Creates num evenly spaced values between start and stop.

In [6]:
l = np.linspace(0, 1 , 5)
print("Linspace array:", l)

Linspace array: [0.   0.25 0.5  0.75 1.  ]


## 7. np.random.rand(shape) >Creates an array of random values between 0 and 1.

In [34]:
rand = np.random.rand(2, 3)
print("Random array:\n", rand)

Random array:
 [[0.62528195 0.03110968 0.587652  ]
 [0.37600002 0.4012517  0.55697535]]
