In [1]:
import numpy as np

# 🔰 Section 1: Array Creation & Attributes
## Q1. Create a 5x5 matrix with values from 1 to 25.
## Then, print:

## Shape, size, number of dimensions

## Data type of elements

In [5]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(5, 5)
25
2
int64


# 🔰 Section 2: Indexing, Slicing, Reversing
## Q2. Slice the center 3x3 block from the matrix above.
## Q3. Reverse the matrix along:
## Rows (top to bottom)

## Columns (left to right)


In [7]:
#Q.2
print(arr[1:4 , 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [16]:
#Q.3
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print(arr[::-1],'\n')
print(arr[::])

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# 🔰 Section 3: Boolean Masking & Conditional Selection
## Q4. Extract all even numbers from the matrix using boolean masking.
## Q5. Replace all odd numbers in the matrix with -1.

In [4]:
#Q.4
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
mask = arr % 2==0
print(arr[mask])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [5]:
# Q.5
arr[arr % 2 != 0] = -1
print(arr)

[[-1  2 -1  4 -1]
 [ 6 -1  8 -1 10]
 [-1 12 -1 14 -1]
 [16 -1 18 -1 20]
 [-1 22 -1 24 -1]]


# 🔰 Section 4: Fancy Indexing & Multi-dimensional Indexing
## Q6. Given this matrix:
## matrix = np.array([
## [10, 20, 30],
##                    [40, 50, 60],
##                    [70, 80, 90]
## ])

## Use fancy indexing to extract the diagonal elements using:
## row = [0, 1, 2]
## col = [0, 1, 2]

In [7]:
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
row = [0,1,2]
col = [0,1,2]
print(matrix[row,col])

[10 50 90]


#  🔰 Section 5: Aggregation & Vectorized Ops
##  Q7. Calculate:
##  Row-wise sum
##  Column-wise mean
##  Overall standard deviation

In [9]:
print(np.mean(matrix,axis =0))
print(np.std(matrix))

[40. 50. 60.]
25.81988897471611


# 🔰 Section 6: Dot Product & Matrix Multiplication
## Q8. Create two 2×2 matrices:

## A = np.array([[1, 2], [3, 4]])
## B = np.array([[5, 6], [7, 8]])
## Find dot product: np.dot(A, B)

## Try A @ B

In [3]:
import numpy as np
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
print(np.dot(A,B))
print(A @ B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
