# 🔹 1. Reshape
## ✍️ Explanation:
## reshape() lets you change the shape of an array without changing its data. You must make sure the number of elements remains the same.

In [10]:
import numpy as np
a = np.arange(12)
reshaped = a.reshape(2,6)
print(reshaped)

b = np.arange(2,34,2)
print(b.reshape(4,4))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


# 🔹 2. Flatten
## ✍️ Explanation:
## flatten() converts a multi-dimensional array to 1D. It returns a copy, so changes won’t affect the original array.

In [12]:
arr = np.array([
    [1,2],
    [3,4]
])
flat = arr.flatten()  #converts the multidimensional array into a 1D array
print(flat)

[1 2 3 4]


In [16]:
arr3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
flat3 = arr3.flatten()
print(flat3)
arr3[arr3>5] = 0
print(flat3) #after modifying the original array the flatten value does not changes
print(arr3)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 0]
 [0 0 0]]


# 🔹 3. Ravel
## ✍️ Explanation:
## Like flatten(), but returns a view, not a copy — meaning any changes in the original will reflect in the raveled array.

In [21]:
a = np.array([[1,2],[3,4]])
r = a.ravel()
print(r)
a[0,0] =100
print(r) # <- reflects the changes in the raveled array

[1 2 3 4]
[100   2   3   4]


# 🔹 4. Transpose
## ✍️ Explanation:
## transpose() or .T swaps rows with columns. It’s used in matrix math or converting shape from (m, n) to (n, m).

In [22]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


#  5. Concatenate
## ✍️ Explanation:
## Joins two or more arrays along an axis using np.concatenate().

In [29]:
a = np.array([[1,2]])
b = np.array([[3,4]])
print(np.concatenate((a,b) ,axis=0))  #vertical join
print(np.concatenate((a,b), axis=1))  #horizontal join

[[1 2]
 [3 4]]
[[1 2 3 4]]


# 🔹 6. vstack (Vertical Stack)
## ✍️ Explanation:
## vstack() stacks arrays vertically (row-wise) — the number of columns must match.

In [33]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])
v = np.vstack((a, b))
print(v)

[[1 2]
 [3 4]]


In [34]:
c = ([[5,6]])
vs = np.vstack((a,b,c))
print(vs)

[[1 2]
 [3 4]
 [5 6]]


# 🔹 7. hstack (Horizontal Stack)
## ✍️ Explanation:
## hstack() stacks arrays horizontally (column-wise) — the number of rows must match.

In [38]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
h = np.hstack((a, b))
print(h)

[[1 2 5 6]
 [3 4 7 8]]


# 🔹 8. split
## ✍️ Explanation:
## split() divides an array into equal parts along the specified axis.

In [48]:
x = np.arange(12).reshape(3,4)
print(x)
s = np.split(x , 2 , axis = 1)
for part in s:
    print(part)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


# 🔹 9. vsplit (Vertical Split)
## ✍️ Explanation:
## vsplit() splits arrays vertically (row-wise) — shorthand for split(..., axis=0)

In [49]:
x = np.arange(12).reshape(3, 4)
print(x)
vs = np.vsplit(x, 3)
for part in vs:
    print(part)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]


# 🔹 10. hsplit (Horizontal Split)
## ✍️ Explanation:
## hsplit() splits arrays horizontally (column-wise) — shorthand for split(..., axis=1)

In [52]:
print(x)
hs = np.hsplit(x, 4)
for part in hs:
    print(part)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [4]
 [8]]
[[1]
 [5]
 [9]]
[[ 2]
 [ 6]
 [10]]
[[ 3]
 [ 7]
 [11]]


# 🔹 11. Changing Dimensions
## ✍️ Explanation:
## You can manually add dimensions to 1D arrays using np.newaxis or reshape().

## Convert 1D to Row Vector:

In [54]:
a = np.array([1, 2, 3, 4])
row = a[np.newaxis, :]
print(row, row.shape)  # shape = (1, 4)
print(a.shape)

[[1 2 3 4]] (1, 4)
(4,)


## Convert 1D to Column Vector:

In [55]:
col = a[:, np.newaxis]
print(col, col.shape)  # shape = (4, 1)

[[1]
 [2]
 [3]
 [4]] (4, 1)
